name: NodejsCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: CreadorCraft-Maker-Flash
        uses: ./
        with:
            path: './test'
            pathSWF: 'game.swf'
            elementID: 'Test'
      - name: CreadorCraft-Maker
        uses: Creadores-Program/CreadorCraft-Maker-GHA@v1.1.0
        with:
            path: './test'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: GameFlash Example
            path: gameBuildCCM/CreadorCraft Game 1.0.0.creadorcraftgame.zip
